# Generated by Django 2.1.2 on 2019-06-14 23:56

from django.db import migrations, models
import django.db.models.deletion
import targets.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('uuid4', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=256)),
                ('website_url', models.CharField(max_length=1024)),
                ('icon', models.ImageField(upload_to=targets.models.get_version_png_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='TargetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.CharField(max_length=16)),
                ('uuid4', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='targets.Target')),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='latest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='targets.TargetVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='targetversion',
            unique_together={('target', 'version_number')},
        ),
    ]
