# Generated by Django 2.1.2 on 2019-06-15 04:04

from django.db import migrations, models
import targets.models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='latest',
        ),
        migrations.AlterField(
            model_name='target',
            name='icon',
            field=models.ImageField(upload_to=targets.models.get_version_png_filepath),
        ),
    ]
